# Conda environment for telescope-layouts
# 
# Install: 
# conda env create -f environment.yml
# conda activate telescopes
# 
name: telescopes

dependencies:
  - python==3.7
  - proj
  - pep8
  - pylint
  - numpy
  - astropy
  - matplotlib
  - yaml
