# Conda environment for telescope-layouts
#
# Install:
# conda env create -f environment.yml
# conda activate telescope-layouts
#
name: telescope-layouts

dependencies:
  - astropy
  - python
  - pyproj
  - pyyaml
  - pep8
  - pylint
  - numpy
  - matplotlib
  - yaml
